Added ojAlgo lib for linear optimization Issues: 	- MainActivity:119 throws NoClassDefFoundError because it does not find org.ojalgo.optimisation.integer.IntegerSolver$BranchAndBoundNodeTask at runtime. Works with normal java applications however, maybe sth to do with java version? 	- ListAdapter implementation still pending, therefore put code for displaying pizzas in comments